# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('qq_number', models.IntegerField(blank=True, max_length=15, null=True)),
                ('sex', models.CharField(choices=[('girl', '女'), ('secret', '保密'), ('boy', '男')], max_length=10)),
                ('avatar', models.ImageField(upload_to='profile_image')),
                ('belong_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('url_image', models.URLField(blank=True, null=True)),
                ('cover', models.FileField(null=True, upload_to='cover_image')),
                ('editors_choice', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='firstapp.UserProfile')),
            ],
        ),
    ]
