# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20170824_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='loginer',
        ),
        migrations.AlterField(
            model_name='save',
            name='save_choice',
            field=models.CharField(choices=[('save', 'save'), ('saved', 'saved')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='choice',
            field=models.CharField(choices=[('dislike', 'dislike'), ('like', 'like'), ('normal', 'normal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('girl', '女'), ('boy', '男'), ('secret', '保密')], max_length=10),
        ),
    ]
