# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0028_auto_20170919_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='guanZhuOrNot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cmtticket',
            name='choice',
            field=models.CharField(choices=[('normal', 'normal'), ('like', 'like'), ('dislike', 'dislike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='choice',
            field=models.CharField(choices=[('normal', 'normal'), ('like', 'like'), ('dislike', 'dislike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('boy', '男'), ('girl', '女'), ('secret', '保密')], max_length=10),
        ),
    ]
