# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0031_auto_20170920_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followings',
            name='following',
        ),
        migrations.AddField(
            model_name='followers',
            name='followerId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='followings',
            name='followingId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='followings',
            name='followings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='firstapp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='followers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='firstapp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('boy', '男'), ('girl', '女'), ('secret', '保密')], max_length=10),
        ),
    ]
