# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0033_auto_20170921_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sixin',
            old_name='comment',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='cmtticket',
            name='choice',
            field=models.CharField(choices=[('normal', 'normal'), ('dislike', 'dislike'), ('like', 'like')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='choice',
            field=models.CharField(choices=[('normal', 'normal'), ('dislike', 'dislike'), ('like', 'like')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('girl', '女'), ('boy', '男'), ('secret', '保密')], max_length=10),
        ),
    ]
