# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0034_auto_20170921_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='siXinNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='save',
            name='save_choice',
            field=models.CharField(choices=[('saved', 'saved'), ('save', 'save')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('secret', '保密'), ('girl', '女'), ('boy', '男')], max_length=10),
        ),
    ]
