# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0037_auto_20170928_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pingLunNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='save',
            name='save_choice',
            field=models.CharField(choices=[('saved', 'saved'), ('save', 'save')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('boy', '男'), ('girl', '女'), ('secret', '保密')], max_length=10),
        ),
    ]
