# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0039_auto_20171002_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmtticket',
            name='createtime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='save',
            name='save_choice',
            field=models.CharField(choices=[('save', 'save'), ('saved', 'saved')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('girl', '女'), ('secret', '保密'), ('boy', '男')], max_length=10),
        ),
    ]
