# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0040_auto_20171003_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmtticket',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmtuser_tickets', to='firstapp.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('secret', '保密'), ('boy', '男'), ('girl', '女')], max_length=10),
        ),
    ]
