# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-03 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0041_auto_20171003_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='save',
            name='createtime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cmtticket',
            name='choice',
            field=models.CharField(choices=[('like', 'like'), ('normal', 'normal'), ('dislike', 'dislike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='createtime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentcmt',
            name='createtime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='save',
            name='save_choice',
            field=models.CharField(choices=[('saved', 'saved'), ('save', 'save')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sixin',
            name='createtime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='choice',
            field=models.CharField(choices=[('like', 'like'), ('normal', 'normal'), ('dislike', 'dislike')], max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='createtime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
