# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0045_auto_20171011_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='save_choice',
            field=models.CharField(choices=[('saved', 'saved'), ('save', 'save')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('girl', '女'), ('boy', '男'), ('secret', '保密')], max_length=10),
        ),
    ]
